### ISSUE TITLE
would you recommend a micro-memoize formula for me?

### ISSUE THREAD

**Issue by iambumblehead** [planttheidea/micro-memoize#78]
Hello,

For a long-running web-sevice, I'd like async data to be auto-removed from the memoization-cache every 20 minutes. Is there a micro-memoize formula solution to this problem?

I've been using micro-memoize for a year or two now and its been great. Thank you for any response you may have.

**Comment by planttheidea** [comment]
So, I see this as two separate questions:

1. How can I clear the cache of my memoized function?
2. How can I manage the clearance of my cache, based on requirements?

**How can I clear the cache of my memoized function?**

The cache for the function is stored on the function itself, and the cache is really just an instance with `keys` / `values`, both arrays, so you could create a clearance function that can handle this fairly easily:

```ts
function clearMemoizedCache(fn) {
  fn.cache.keys.length = fn.cache.values.length = 0;
}
```

Notice I am retaining the original references; to avoid garbage cycling, mutation is heavily used internally by the cache, so you can't just do `fn.cache.keys = []` because some things will break.

If you want a more convenient mechanism, you could create a thin abstraction to attach this to the function:

```ts
import microMemoize from 'micro-memoize';

function memoize(fn) {
  const memoized = microMemoize(fn);

  memoized.clearCache = () => {
    memoized.cache.keys.length = memoized.cache.values.length = 0;
  };

  return memoized;
}
```

**How can I manage the clearance of my cache, based on requirements?**

By creating simple abstractions like above, you can programmatically trigger the cache clearance based on your needs. You mention wanting to clear out the cache every 20 minutes, so it could just simple as `setInterval` that runs in the background:

```ts
setInterval(() => clearMemoizedCache(fn));
```

If you want something more granular, like "clear the cache if there have been no updates for 20 minutes", then you can use the optional callbacks to debounce the clearance:

```ts
function createStaleCacheManager() {
  let timeoutId = null;

  return function (cache) {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    
    timeoutId = setTimeout(() => {
      timeoutId = null;
      cache.keys.length = cache.values.length = 0;
    }, 1000 * 60 * 20);
  };
}

const staleCacheManager = createStaleCacheManager();
const memoized = memoize(fn, {
  isPromise: true,
  onCacheAdd: staleCacheManager,
  onCacheChange: staleCacheManager,
});
```

This is just off the top of the head, but there are a number of ways to manage programmatic clearance.

**Food for thought**

You might consider changing to use the superset of `micro-memoize`: [`moize`](https://github.com/planttheidea/moize). It allows for finer-grained cache control in a number of ways, and for the use-case you describe it has a [`maxAge` option](https://github.com/planttheidea/moize#maxage) which would automatically remove an entry from cache if it is older than 20 minutes.

Hope this was helpful, but if not happy to rubber duck some more.

**Comment by iambumblehead** [comment]
@planttheidea thank you for the helpful and thoughtful answer. I understand and will follow your suggestion.
